"""Initial migration

Revision ID: 66d838b809c5
Revises: 
Create Date: 2024-06-17 17:50:05.274143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d838b809c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('Contract_Number', sa.Integer(), nullable=False),
    sa.Column('Organization_Type', sa.String(length=255), nullable=False),
    sa.Column('Ministry', sa.String(length=255), nullable=False),
    sa.Column('Department', sa.String(length=255), nullable=False),
    sa.Column('Organization_Name', sa.String(length=50), nullable=True),
    sa.Column('Office_Zone', sa.String(length=50), nullable=True),
    sa.Column('Buyer_Designation', sa.String(length=255), nullable=False),
    sa.Column('Buying_Mode', sa.String(length=255), nullable=False),
    sa.Column('Contract_Date', sa.Date(), nullable=False),
    sa.Column('Total', sa.Float(), nullable=False),
    sa.Column('Product', sa.String(length=255), nullable=False),
    sa.Column('Brands', sa.String(length=255), nullable=False),
    sa.Column('Models', sa.String(length=255), nullable=False),
    sa.Column('Quantities', sa.Integer(), nullable=False),
    sa.Column('Prices', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Contract_Number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
