"""My first migration

Revision ID: c8c30d8b7360
Revises: 66d838b809c5
Create Date: 2024-11-14 17:26:41.854306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c30d8b7360'
down_revision = '66d838b809c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('gem_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_name')
    # ### end Alembic commands ###
